manifest:
  remotes:
    - name: benvallack
      url-base: https://github.com/benvallack
  projects:
    - name: zmk
      remote: benvallack
      revision: mouse-pr
      import: app/west.yml
  self:
    path: config
